### ISSUE TITLE
Switch to query-string routing

### ISSUE THREAD

**Issue by denis-ok** [bloodyowl/reshowcase#15]
I worked on a small feature allowing build reshowcase js bundle (to upload it somewhere) and found that the current routing approach with paths doesn't allow to work with built bundle out of the box.

As I understand, the routing in a served built app doesn't work because it requires a server specially configured to respond with `index.html` on any path like `reshowcase/Button/normal`.

Yeah, this kind of URLs looks good. But we can't just build and upload reshowcase bundle somewhere and expect that it will work.

Maybe it's not a big problem, actually.

I found that Storybook and React Cosmos are using the query-string routing approach which probably doesn't have this problem because the path is not changing, only parameters.

@bloodyowl What do you think? Can we switch to a query-string routing approach?

To something like this: `/?demo=Button&demoUnit=normal`

Am I missing something?

**Comment by bloodyowl** [comment]
Done in https://github.com/bloodyowl/reshowcase/commit/07165a9207da94ed852c990ca6c647838d879542
